/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btnhom1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Linh Liv
 */
public class frmThemSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form frmThemSinhVien
     */
    QLSinhVien qlsv = null;
    SinhVien[] arrSVs = null;
    String maSV;

    public frmThemSinhVien() throws IOException, ClassNotFoundException {
        initComponents();
        myinit();
    }

    private void setMaSV() {
        arrSVs = qlsv.getArrSVs();
        if (arrSVs == null) {
            maSV = "SV00001";
        } else {
            String maLastSV = arrSVs[arrSVs.length - 1].getMaSV();
            maSV = (Helper.tangKey(maLastSV));
        }
    }

    private void myinit() throws IOException, ClassNotFoundException {
        qlsv = new QLSinhVien();
        this.setMaSV();
        txtMaSV.setText(maSV);
        QLNganh qlnganh = null;
        try {
            qlnganh = new QLNganh();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(frmThemSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel listTuoi = new DefaultComboBoxModel();
        DefaultComboBoxModel listNganh = new DefaultComboBoxModel();
        for (int i = 18; i <= 99; i++) {
            listTuoi.addElement(i);
        }
        cbTuoi.setModel(listTuoi);
        for (String maNganh : qlnganh.getMaNganh()) {
            listNganh.addElement(maNganh);
        }
        cbNganh.setModel(listNganh);
    }

    private void reset() {
        this.setMaSV();
        txtMaSV.setText(maSV);
        txtHoTen.setText("");
        txtLop.setText("");
        txtMatKhau.setText("");
        //reset combobox vs sltGioi TInh
//        cbTuoi.getModel().setSelectedItem("18");
//        cbNganh.getModel().setSelectedItem("1 - An Toàn Thông Tin");
//        sltNam.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sltGrGioiTinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtMaSV = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        cbTuoi = new javax.swing.JComboBox<>();
        txtLop = new javax.swing.JTextField();
        sltNu = new javax.swing.JRadioButton();
        sltNam = new javax.swing.JRadioButton();
        cbNganh = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Thêm Sinh Viên");

        jLabel2.setText("Mã sinh viên: ");

        jLabel3.setText("Họ tên: ");

        jLabel4.setText("Mật Khẩu: ");

        jLabel5.setText("Tuổi:");

        jLabel6.setText("Lớp: ");

        jLabel7.setText("Giới tính: ");

        jLabel8.setText("Ngành: ");

        txtMaSV.setEnabled(false);

        sltGrGioiTinh.add(sltNu);
        sltNu.setText("Nữ");
        sltNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sltNuActionPerformed(evt);
            }
        });

        sltGrGioiTinh.add(sltNam);
        sltNam.setSelected(true);
        sltNam.setText("Nam");

        cbNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNganhActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLop)
                            .addComponent(txtMaSV)
                            .addComponent(txtHoTen)
                            .addComponent(txtMatKhau)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sltNam)
                                .addGap(39, 39, 39)
                                .addComponent(sltNu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset))
                            .addComponent(cbNganh, 0, 256, Short.MAX_VALUE)
                            .addComponent(cbTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sltNu)
                    .addComponent(sltNam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnReset))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if (!txtHoTen.getText().trim().isEmpty()) {
            if (!txtLop.getText().trim().isEmpty()) {
                if (!txtMaSV.getText().trim().isEmpty()) {
                    if (!txtMatKhau.getPassword().equals("")) {
                        //không có trường nào trống
                        String gioiTinh = "Nam";
                        if (sltNu.isSelected()) {
                            gioiTinh = "Nữ";
                        }
//                         System.out.println(sltNam.isSelected());
//                         System.out.println(cbNganh.getModel().getSelectedItem());
                        int nganh = Integer.parseInt(cbNganh.getModel().getSelectedItem().toString().substring(0, 1));
                        SinhVien sv = new SinhVien(
                                txtMaSV.getText(),
                                Helper.getMD5(String.copyValueOf(txtMatKhau.getPassword())),
                                txtHoTen.getText().trim(),
                                gioiTinh,
                                Integer.parseInt(cbTuoi.getModel().getSelectedItem().toString()),
                                nganh
                        );
                        qlsv.addSinhVien(sv);
                        try {
                            qlsv.ghi();
                            this.reset();
                            JOptionPane.showMessageDialog(null, "Thêm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        } catch (IOException ex) {
                            Logger.getLogger(frmThemSinhVien.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        return;
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Nhập thiếu trường", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnThemActionPerformed

    private void cbNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNganhActionPerformed

    private void sltNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sltNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sltNuActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.reset();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new frmThemSinhVien().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(frmThemSinhVien.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbNganh;
    private javax.swing.JComboBox<String> cbTuoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.ButtonGroup sltGrGioiTinh;
    private javax.swing.JRadioButton sltNam;
    private javax.swing.JRadioButton sltNu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
